### ISSUE TITLE
How to contribute to this repository.

### ISSUE THREAD

**Issue by talk2sohail** [jmpsec/osctrl#350]
Hi,

My name is Md Sohail. I have been working as  a Software Engineer for the past 2 years. I recently discovered Osquery in my workplace and wanted to learn more. So I came across this project which is extensively using Osquery. 

I wanted to  upskill myself by contributing any way possible. 

Can anyone please tell me how can I get started? 

I have basic knowledge  of Osquery ( Like making queries, setting up the service for custom config, etc ) and little working knowledge of Go as well. Thanking with anticipation. 

Regards,
Sohail

**Comment by javuto** [comment]
Hi Sohail! The first step would be to deploy **osctrl** in a Linux environment or a Docker environment, and start taking notes right away. Because if there are issues with the deployment, then there are problems with the `provision.sh` or the `dockerize.sh`/`docker-compose.yml`. Those can be turned into issues and eventually will get fixed, or even better, you can attempt to fix them and submit a Pull Request!

If you are more interested in the codebase, rather than the deployment aspect, another good way to understand what the different components are doing is to write unit tests, since our coverage is still quite low.

How does it sound? Thank you for helping with **osctrl**!

**Comment by javuto** [comment]
You can still use the `provision.sh` script, but the docker environment has been changed so now if you want to use docker you can just run `make docker_dev` which will run `make docker_dev_build` and `make docker_dev_up`.

Hope that helps! Thanks!
